# Data Science Interview Preparation Code: Pandas & Scikit-learn

This notebook compiles essential interview questions and solutions for Pandas and Scikit-learn, suitable for data scientists with 3 years of experience. It covers data manipulation, preprocessing, model training, and evaluation.


In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'OrderID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1],
    'CustomerID': [101, 102, 101, 103, 102, 104, 101, 103, 105, 104, 101],
    'OrderDate': pd.to_datetime(['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-05', '2024-02-10',
                                  '2024-03-01', '2024-03-05', '2024-03-10', '2024-03-15', '2024-04-01', '2024-01-15']),
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop',
                'Mouse', 'Laptop', 'Keyboard', 'Monitor', 'Mouse', 'Laptop'],
    'Quantity': [1, 2, 1, 1, 1, 3, 2, 1, 1, 2, 1],
    'Price': [1200, 25, 75, 300, 1150, 20, 1250, 80, 320, 22, 1200]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("-" * 30)

Original DataFrame:
    OrderID  CustomerID  OrderDate   Product  Quantity  Price
0         1         101 2024-01-15    Laptop         1   1200
1         2         102 2024-01-20     Mouse         2     25
2         3         101 2024-02-01  Keyboard         1     75
3         4         103 2024-02-05   Monitor         1    300
4         5         102 2024-02-10    Laptop         1   1150
5         6         104 2024-03-01     Mouse         3     20
6         7         101 2024-03-05    Laptop         2   1250
7         8         103 2024-03-10  Keyboard         1     80
8         9         105 2024-03-15   Monitor         1    320
9        10         104 2024-04-01     Mouse         2     22
10        1         101 2024-01-15    Laptop         1   1200
------------------------------


## Question 1: Data Inspection

Task: Display the first 5 rows of the DataFrame, its column names and their data types, and check for any missing values across all columns.

Expected Output: df.head(), df.info(), df.isnull().sum()

In [3]:
print("Q1: Head of DataFrame:")
print(df.head())
print("\nQ1: DataFrame Info:")
df.info()
print("\nQ1: Missing values:")
print(df.isnull().sum())
print("-" * 30)

Q1: Head of DataFrame:
   OrderID  CustomerID  OrderDate   Product  Quantity  Price
0        1         101 2024-01-15    Laptop         1   1200
1        2         102 2024-01-20     Mouse         2     25
2        3         101 2024-02-01  Keyboard         1     75
3        4         103 2024-02-05   Monitor         1    300
4        5         102 2024-02-10    Laptop         1   1150

Q1: DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   OrderID     11 non-null     int64         
 1   CustomerID  11 non-null     int64         
 2   OrderDate   11 non-null     datetime64[ns]
 3   Product     11 non-null     object        
 4   Quantity    11 non-null     int64         
 5   Price       11 non-null     int64         
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 660.0+ bytes

Q1: Missing values:
OrderID  

## Question 2: Create a New Column (Total Price)

Task: Add a new column named TotalPrice to the DataFrame, which is calculated as Quantity * Price.

Expected Output: DataFrame with the new TotalPrice column.

In [4]:
df['TotalPrice'] = df['Quantity'] * df['Price']
print("DataFrame with TotalPrice column:")
print(df)
print("-" * 30)

DataFrame with TotalPrice column:
    OrderID  CustomerID  OrderDate   Product  Quantity  Price  TotalPrice
0         1         101 2024-01-15    Laptop         1   1200        1200
1         2         102 2024-01-20     Mouse         2     25          50
2         3         101 2024-02-01  Keyboard         1     75          75
3         4         103 2024-02-05   Monitor         1    300         300
4         5         102 2024-02-10    Laptop         1   1150        1150
5         6         104 2024-03-01     Mouse         3     20          60
6         7         101 2024-03-05    Laptop         2   1250        2500
7         8         103 2024-03-10  Keyboard         1     80          80
8         9         105 2024-03-15   Monitor         1    320         320
9        10         104 2024-04-01     Mouse         2     22          44
10        1         101 2024-01-15    Laptop         1   1200        1200
------------------------------


## Question 3: Filtering Data

Task: Filter the DataFrame to show only orders where the Product is 'Laptop' and the Quantity is greater than 1.

Expected Output: Filtered DataFrame.

In [5]:
filtered_df = df[(df['Product'] == 'Laptop') & (df['Quantity'] > 1)]
print("Filtered DataFrame:")
print(filtered_df)
print("-" * 30)

Filtered DataFrame:
   OrderID  CustomerID  OrderDate Product  Quantity  Price  TotalPrice
6        7         101 2024-03-05  Laptop         2   1250        2500
------------------------------


## Question 4: Grouping and Aggregation

Task: Calculate the total TotalPrice for each CustomerID.

Expected Output: A Series or DataFrame showing CustomerID and their aggregated TotalPrice.

In [6]:
grp_df = df.groupby('CustomerID')['TotalPrice'].sum().reset_index()
print("Grouped DataFrame by CustomerID:")
print(grp_df)
print("-" * 30)

Grouped DataFrame by CustomerID:
   CustomerID  TotalPrice
0         101        4975
1         102        1200
2         103         380
3         104         104
4         105         320
------------------------------


## Question 5: Sorting Data

Task: Sort the DataFrame first by OrderDate in ascending order, and then by TotalPrice in descending order.

Expected Output: Sorted DataFrame.

In [7]:
sorted_df = df.sort_values(by=['OrderDate', 'TotalPrice'], ascending=[True, False])
print("Sorted DataFrame:")
print(sorted_df)
print("-" * 30)

Sorted DataFrame:
    OrderID  CustomerID  OrderDate   Product  Quantity  Price  TotalPrice
0         1         101 2024-01-15    Laptop         1   1200        1200
10        1         101 2024-01-15    Laptop         1   1200        1200
1         2         102 2024-01-20     Mouse         2     25          50
2         3         101 2024-02-01  Keyboard         1     75          75
3         4         103 2024-02-05   Monitor         1    300         300
4         5         102 2024-02-10    Laptop         1   1150        1150
5         6         104 2024-03-01     Mouse         3     20          60
6         7         101 2024-03-05    Laptop         2   1250        2500
7         8         103 2024-03-10  Keyboard         1     80          80
8         9         105 2024-03-15   Monitor         1    320         320
9        10         104 2024-04-01     Mouse         2     22          44
------------------------------


## Question 6: Handling Duplicates (Conceptual & Practical)

Task:

Conceptual: If you had duplicate rows (e.g., identical OrderID, CustomerID, Product, etc.), how would you identify them?

Practical: (No actual duplicates in our sample data, but assume you need to demonstrate the method) Write code to remove duplicates based on OrderID, keeping the first occurrence.

Expected Output:

Conceptual explanation.

DataFrame with duplicates removed (if any were present).

In [8]:
drop_duplicates_df = df.drop_duplicates(subset=['OrderID'], keep='first')
print("DataFrame after dropping duplicates:")
print(drop_duplicates_df)
print("-" * 30)

DataFrame after dropping duplicates:
   OrderID  CustomerID  OrderDate   Product  Quantity  Price  TotalPrice
0        1         101 2024-01-15    Laptop         1   1200        1200
1        2         102 2024-01-20     Mouse         2     25          50
2        3         101 2024-02-01  Keyboard         1     75          75
3        4         103 2024-02-05   Monitor         1    300         300
4        5         102 2024-02-10    Laptop         1   1150        1150
5        6         104 2024-03-01     Mouse         3     20          60
6        7         101 2024-03-05    Laptop         2   1250        2500
7        8         103 2024-03-10  Keyboard         1     80          80
8        9         105 2024-03-15   Monitor         1    320         320
9       10         104 2024-04-01     Mouse         2     22          44
------------------------------


## Question 7: Time-based Filtering

Task: Filter the DataFrame to show all orders placed in the month of March 2024.

Expected Output: Filtered DataFrame.

In [9]:
filter_order_df = df[(df['OrderDate'] >= '2024-03-01') & (df['OrderDate'] < '2024-04-01')]
print("Filtered DataFrame by OrderDate:")
print(filter_order_df)

Filtered DataFrame by OrderDate:
   OrderID  CustomerID  OrderDate   Product  Quantity  Price  TotalPrice
5        6         104 2024-03-01     Mouse         3     20          60
6        7         101 2024-03-05    Laptop         2   1250        2500
7        8         103 2024-03-10  Keyboard         1     80          80
8        9         105 2024-03-15   Monitor         1    320         320


## Question 8: Conditional Value Assignment (.loc or np.where)

Task: Create a new column called OrderCategory. If TotalPrice is greater than 500, assign 'High Value', otherwise assign 'Standard Value'.

Expected Output: DataFrame with the new OrderCategory column.

In [10]:
df['OrderCategory'] = np.where(df['TotalPrice'] > 500, 'High Value', 'Standard Value')
print("DataFrame with OrderCategory column:")
print(df)
print("-" * 30)

DataFrame with OrderCategory column:
    OrderID  CustomerID  OrderDate   Product  Quantity  Price  TotalPrice  \
0         1         101 2024-01-15    Laptop         1   1200        1200   
1         2         102 2024-01-20     Mouse         2     25          50   
2         3         101 2024-02-01  Keyboard         1     75          75   
3         4         103 2024-02-05   Monitor         1    300         300   
4         5         102 2024-02-10    Laptop         1   1150        1150   
5         6         104 2024-03-01     Mouse         3     20          60   
6         7         101 2024-03-05    Laptop         2   1250        2500   
7         8         103 2024-03-10  Keyboard         1     80          80   
8         9         105 2024-03-15   Monitor         1    320         320   
9        10         104 2024-04-01     Mouse         2     22          44   
10        1         101 2024-01-15    Laptop         1   1200        1200   

     OrderCategory  
0       High Valu

## Question 9: Pivot Table / Crosstab (Conceptual)

Task: How would you use Pandas to create a table showing the total Quantity sold for each Product across different OrderCategorys (from Q8)?

Expected Output: Conceptual explanation using pivot_table or groupby and unstack

In [11]:
pivot_df = df.pivot_table(index='Product', columns='OrderCategory', values='Quantity', aggfunc='sum', fill_value=0)
print("Pivot Table:")
print(pivot_df)
print("-" * 30)

Pivot Table:
OrderCategory  High Value  Standard Value
Product                                  
Keyboard                0               2
Laptop                  5               0
Monitor                 0               2
Mouse                   0               7
------------------------------


In [12]:
import pandas as pd
import numpy as np

orders_data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'CustomerID': [1, 2, 1, 3, 2, 4, 1, 3, 5, 4],
    'OrderDate': pd.to_datetime(['2023-01-05', '2023-01-10', '2023-01-15', '2023-01-20', '2023-02-01',
                                  '2023-02-05', '2023-02-10', '2023-02-15', '2023-03-01', '2023-03-05']),
    'Product': ['A', 'B', 'A', 'C', 'B', 'D', 'A', 'C', 'E', 'D'],
    'Quantity': [2, 1, 3, 1, 2, 1, 1, 2, 1, 3],
    'PricePerUnit': [50.0, 75.0, 50.0, 100.0, 75.0, 120.0, 50.0, 100.0, 90.0, 120.0]
}
df_orders = pd.DataFrame(orders_data)
df_orders['TotalAmount'] = df_orders['Quantity'] * df_orders['PricePerUnit']

print("DataFrame: df_orders")
print(df_orders)
print("-" * 50)


customers_data = {
    'CustomerID': [1, 2, 3, 4, 5, 6],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Los Angeles', 'Houston'],
    'JoinDate': pd.to_datetime(['2022-01-01', '2022-03-15', '2022-05-01', '2022-07-20', '2022-09-10', '2022-11-01'])
}
df_customers = pd.DataFrame(customers_data)

print("DataFrame: df_customers")
print(df_customers)
print("-" * 50)

DataFrame: df_orders
   OrderID  CustomerID  OrderDate Product  Quantity  PricePerUnit  TotalAmount
0      101           1 2023-01-05       A         2          50.0        100.0
1      102           2 2023-01-10       B         1          75.0         75.0
2      103           1 2023-01-15       A         3          50.0        150.0
3      104           3 2023-01-20       C         1         100.0        100.0
4      105           2 2023-02-01       B         2          75.0        150.0
5      106           4 2023-02-05       D         1         120.0        120.0
6      107           1 2023-02-10       A         1          50.0         50.0
7      108           3 2023-02-15       C         2         100.0        200.0
8      109           5 2023-03-01       E         1          90.0         90.0
9      110           4 2023-03-05       D         3         120.0        360.0
--------------------------------------------------
DataFrame: df_customers
   CustomerID     Name         City

## Question 1: Merging DataFrames

Task: Merge df_orders and df_customers to include customer Name and City in the orders DataFrame. Perform an inner join.

Expected Output: A new DataFrame df_merged_orders with OrderID, CustomerID, OrderDate, Product, Quantity, PricePerUnit, TotalAmount, Name, and City.

In [13]:
df_merged = pd.merge(df_orders, df_customers[['CustomerID', 'Name','City']], on = 'CustomerID', how = 'left')
print("Merged DataFrame:")
print(df_merged)

Merged DataFrame:
   OrderID  CustomerID  OrderDate Product  Quantity  PricePerUnit  \
0      101           1 2023-01-05       A         2          50.0   
1      102           2 2023-01-10       B         1          75.0   
2      103           1 2023-01-15       A         3          50.0   
3      104           3 2023-01-20       C         1         100.0   
4      105           2 2023-02-01       B         2          75.0   
5      106           4 2023-02-05       D         1         120.0   
6      107           1 2023-02-10       A         1          50.0   
7      108           3 2023-02-15       C         2         100.0   
8      109           5 2023-03-01       E         1          90.0   
9      110           4 2023-03-05       D         3         120.0   

   TotalAmount     Name         City  
0        100.0    Alice     New York  
1         75.0      Bob  Los Angeles  
2        150.0    Alice     New York  
3        100.0  Charlie      Chicago  
4        150.0      Bob  Lo

## Question 2: Handling Missing Data (Simulation & Imputation)

Task: Simulate Missing Data: Create a copy of df_orders. In this copy, randomly set 3 PricePerUnit values to np.nan.

Impute Missing Data: Fill these missing PricePerUnit values with the mean PricePerUnit of that specific Product. If a product has no previous price to calculate the mean, use the overall mean of the PricePerUnit column.

Expected Output: The modified DataFrame with np.nan values replaced.

In [14]:
df_orders_copy = df_orders.copy()
np.random.seed(42)
random_indices = np.random.choice(df_orders_copy.index, size=3, replace=False)
df_orders_copy.loc[random_indices, 'PricePerUnit'] = np.nan

print(df_orders_copy)

product_means = df_orders_copy.groupby('Product')['PricePerUnit'].transform(lambda x: x.fillna(x.mean()))
# Fill NaNs with product-specific mean, then fill remaining (if product had no valid prices) with overall mean
df_orders_copy['PricePerUnit'] = product_means.fillna(df_orders_copy['PricePerUnit'].mean())

product_means
print(df_orders_copy)

   OrderID  CustomerID  OrderDate Product  Quantity  PricePerUnit  TotalAmount
0      101           1 2023-01-05       A         2          50.0        100.0
1      102           2 2023-01-10       B         1           NaN         75.0
2      103           1 2023-01-15       A         3          50.0        150.0
3      104           3 2023-01-20       C         1         100.0        100.0
4      105           2 2023-02-01       B         2          75.0        150.0
5      106           4 2023-02-05       D         1           NaN        120.0
6      107           1 2023-02-10       A         1          50.0         50.0
7      108           3 2023-02-15       C         2         100.0        200.0
8      109           5 2023-03-01       E         1           NaN         90.0
9      110           4 2023-03-05       D         3         120.0        360.0
   OrderID  CustomerID  OrderDate Product  Quantity  PricePerUnit  TotalAmount
0      101           1 2023-01-05       A         2 

## Question 3: Top N Analysis

Task: Find the top 3 Products by total Quantity sold.

Expected Output: A DataFrame or Series with the top 3 products and their total quantities.

In [15]:
grp_product_df = df_merged.groupby('Product')['Quantity'].sum().nlargest(3).reset_index()

print("Grouped DataFrame by Product:")
print(grp_product_df)

Grouped DataFrame by Product:
  Product  Quantity
0       A         6
1       D         4
2       B         3


## Question 4: Advanced Grouping and Aggregation

Task:

Calculate the total TotalAmount and average Quantity for each City.

For the same aggregation, also find the number of unique Products sold in each city.

Expected Output: A DataFrame grouped by City showing aggregated TotalAmount, Average Quantity, and Unique Products Count.

In [16]:
grp_df = df_merged.groupby('City').agg(Total_Sales=('TotalAmount', 'sum'),
    Average_Quantity=('Quantity', 'mean'),
    Unique_Products_Count=('Product', 'nunique')).reset_index()
print("Grouped DataFrame by City:")
print(grp_df)

Grouped DataFrame by City:
          City  Total_Sales  Average_Quantity  Unique_Products_Count
0      Chicago        300.0          1.500000                      1
1  Los Angeles        315.0          1.333333                      2
2     New York        780.0          2.000000                      2


## Question 5: Time-based Analysis (Monthly Sales)

Task: Calculate the total TotalAmount for each month of the year (based on OrderDate).

Expected Output: A Series or DataFrame showing the month (e.g., '2023-01', '2023-02', etc.) and the corresponding total TotalAmount.

In [17]:
df_orders['OrderMonth'] = df_orders['OrderDate'].dt.to_period('M')

total_sales_month = df_orders.groupby('OrderMonth')['TotalAmount'].sum()
print("Total Sales by Month:")
print(total_sales_month)

Total Sales by Month:
OrderMonth
2023-01    425.0
2023-02    520.0
2023-03    450.0
Freq: M, Name: TotalAmount, dtype: float64


# Sci-Kit Learn

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor
from sklearn.metrics import accuracy_score, mean_squared_error, classification_report, roc_auc_score, r2_score
from sklearn.model_selection import GridSearchCV, KFold

In [19]:
# Generate synthetic data
np.random.seed(42)
n_samples = 500

# Features
age = np.random.randint(20, 60, n_samples)
salary = np.random.randint(30000, 120000, n_samples)
education_level = np.random.choice(['High School', 'Bachelor', 'Master', 'PhD'], n_samples)
experience = np.random.randint(1, 15, n_samples)
city = np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami'], n_samples)
has_loan = np.random.choice([0, 1], n_samples, p=[0.7, 0.3]) # Binary categorical

In [20]:
# Target for Classification (e.g., Customer Churn: 0 = No, 1 = Yes)
# Churn is more likely for older, lower salary, less education, high loan
churn_prob = (
    0.1 * (age / 60) +
    0.05 * (1 - salary / 120000) +
    0.08 * (education_level == 'High School') +
    0.07 * has_loan +
    np.random.rand(n_samples) * 0.1 # Noise
)
churn = (churn_prob > 0.15).astype(int)

# Target for Regression (e.g., Customer Spending)
# Spending is higher for higher salary, more education, more experience
spending = (
    5000 +
    2 * salary / 1000 +
    1000 * (education_level == 'Bachelor') +
    2000 * (education_level == 'Master') +
    3000 * (education_level == 'PhD') +
    200 * experience +
    np.random.randn(n_samples) * 1000 # Noise
)
spending = np.maximum(0, spending) # Ensure no negative spending

In [21]:
data = pd.DataFrame({
    'Age': age,
    'Salary': salary,
    'Education': education_level,
    'Experience': experience,
    'City': city,
    'HasLoan': has_loan,
    'Churn': churn, # Classification target
    'Spending': spending # Regression target
})

print("Sample of the Dataset:")
print(data.head())
print(data.shape)
print("-" * 50)

Sample of the Dataset:
   Age  Salary    Education  Experience         City  HasLoan  Churn  \
0   58   81934     Bachelor          14  Los Angeles        0      1   
1   48   94895  High School           5      Houston        0      1   
2   34   62307       Master           7  Los Angeles        0      0   
3   27   84098       Master           9      Houston        0      0   
4   40   90921          PhD           3      Houston        0      0   

       Spending  
0   8854.759482  
1   5701.192418  
2   8255.619493  
3  10533.367933  
4   7915.975563  
(500, 8)
--------------------------------------------------


**Question 1: Data Splitting**

* **Task:** Split the `data_sk` DataFrame into features (X) and target (y) for the **classification task (`Churn`)**. Then, divide this data into training and testing sets, with 80% for training and 20% for testing. Ensure reproducibility (`random_state=42`) and stratified splitting to maintain class distribution.


In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    data.drop('Churn', axis=1),
    data['Churn'],
    test_size=0.2,
    random_state=42
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((400, 7), (100, 7), (400,), (100,))

**Question 2: Preprocessing - Numerical Features**

* **Task:** For the classification task, identify all numerical features (e.g., `Age`, `Salary`, `Experience`). Create a `StandardScaler` and fit it only on the training data. Transform both the training and testing sets.


In [23]:
numerical_cols = ['Age', 'Salary', 'Experience']
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train[numerical_cols])
X_test_scaled = scaler.transform(X_test[numerical_cols])

print(X_train_scaled[:5])
print(X_test_scaled[:5])

[[-0.11936954  0.05974987  0.8066582 ]
 [ 1.17111196  0.02050751 -1.37023049]
 [ 1.42920826 -1.17283204 -1.61210701]
 [ 1.60127245 -1.54128032  1.04853472]
 [-1.23778683  1.41337462  0.56478167]]
[[ 0.74095146  1.23108163 -0.64460093]
 [ 0.39682306 -1.1020719   0.08102863]
 [ 0.13872676 -0.07051146 -0.40272441]
 [ 1.51524035  1.06073989  1.29041124]
 [ 1.60127245 -0.07040215  1.04853472]]


**Question 3: Preprocessing - Categorical Features (One-Hot Encoding)**

* **Task:** For the classification task, identify the categorical features (`Education`, `City`). Apply `OneHotEncoder` to these features. Fit the encoder only on the training data and transform both training and testing sets.


In [24]:
categorical_cols = ['Education', 'City']
one_code = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_train_encoded = one_code.fit_transform(X_train[categorical_cols])
X_test_encoded = one_code.transform(X_test[categorical_cols])

**Question 4: Full Preprocessing Pipeline with `ColumnTransformer`**

* **Task:** Combine the numerical scaling and categorical one-hot encoding into a single `ColumnTransformer`. Apply this preprocessor to the training and testing sets (`X_train_cls`, `X_test_cls`) for the classification task.
    * Numerical features: `Age`, `Salary`, `Experience`.
    * Categorical features: `Education`, `City`.
    * Features to pass through without transformation: `HasLoan`.


In [25]:
numerical_features_cls = ['Age', 'Salary', 'Experience']
categorical_features_cls = ['Education', 'City']
passthrough_features_cls = ['HasLoan']

preprocessor_cls = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features_cls),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features_cls),
        ('pass', 'passthrough', passthrough_features_cls)
    ],
    remainder='drop' # Drop any columns not specified
)

X_train_cls_processed = preprocessor_cls.fit_transform(X_train)
X_test_cls_processed = preprocessor_cls.transform(X_test)

print(X_train_cls_processed[:5])

[[-0.11936954  0.05974987  0.8066582   0.          0.          0.
   1.          1.          0.          0.          0.          0.
   0.        ]
 [ 1.17111196  0.02050751 -1.37023049  0.          1.          0.
   0.          0.          1.          0.          0.          0.
   1.        ]
 [ 1.42920826 -1.17283204 -1.61210701  0.          0.          1.
   0.          0.          0.          0.          1.          0.
   0.        ]
 [ 1.60127245 -1.54128032  1.04853472  1.          0.          0.
   0.          0.          0.          1.          0.          0.
   0.        ]
 [-1.23778683  1.41337462  0.56478167  0.          0.          1.
   0.          0.          0.          1.          0.          0.
   0.        ]]


**Question 5: Building a Classification Model**

* **Task:** Using the preprocessed data from Q4, train a `LogisticRegression` model to predict `Churn`. Use default parameters. Evaluate its `accuracy_score` and `roc_auc_score` on the test set.


In [26]:
model_lr = LogisticRegression(random_state=42, solver='liblinear') # Using liblinear for robustness
model_lr.fit(X_train_cls_processed, y_train)

y_pred_lr = model_lr.predict(X_test_cls_processed)
y_proba_lr = model_lr.predict_proba(X_test_cls_processed)[:, 1]

print(f"Accuracy: {accuracy_score(y_test, y_pred_lr)}")
print(classification_report(y_test, y_pred_lr))
print(f"ROC AUC Score: {roc_auc_score(y_test, y_pred_lr)}")

Accuracy: 0.85
              precision    recall  f1-score   support

           0       0.79      0.71      0.75        31
           1       0.88      0.91      0.89        69

    accuracy                           0.85       100
   macro avg       0.83      0.81      0.82       100
weighted avg       0.85      0.85      0.85       100

ROC AUC Score: 0.8113604488078543


**Question 6: Building a Regression Model**

* **Task:** Now switch to the **regression task (`Spending`)**. Perform a train-test split (80/20). Using the same `ColumnTransformer` setup as in Q4 (fit on the new training data), preprocess the features. Train a `LinearRegression` model. Evaluate its `mean_squared_error` and `r2_score` on the test set.

In [27]:
X_reg = data.drop('Spending', axis=1)
y_reg = data['Spending']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)


preprocessor_reg = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Age', 'Salary', 'Experience']),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ['Education', 'City']),
        ('pass', 'passthrough', ['HasLoan'])
    ],
    remainder='drop'
)
X_train_reg_processed = preprocessor_reg.fit_transform(X_train_reg)
X_test_reg_processed = preprocessor_reg.transform(X_test_reg)

model_lr_reg = LinearRegression()
model_lr_reg.fit(X_train_reg_processed, y_train_reg)
y_pred_reg = model_lr_reg.predict(X_test_reg_processed)

print(f"Mean Squared Error: {mean_squared_error(y_test_reg, y_pred_reg)}")
print(f"R2 Score Error: {r2_score(y_test_reg, y_pred_reg)}")


Mean Squared Error: 1151586.5375877235
R2 Score Error: 0.598796405302632
